import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const gtStandard = localFont({
  src: [
    {
      path: "./fonts/GT-Standard-L-Standard-Regular-Trial.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GT-Standard-L-Standard-Medium-Trial.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-gt-standard",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gtStandard.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
